- bins/unzzipcat-zip.c
- zzip/zip.c
central directory and/or the offset of start of central directory
point beyond the end of the ZIP file. [CVE-2018-6484]
> Reject the ZIP file and report it as corrupt if the size of the

- zzip/memdisk.c
- zzip/mmapped.c
- If an extension block is too small to hold an extension,
do not use the information therein.
- If the End of central directory record (EOCD) contains an
Offset of start of central directory which is beyond the end of
the file, reject the file.
[CVE-2018-6540]
> Make sure an extension block is large enough.

- config.h.in
- configure
- configure.ac
- zzip/__string.h
The strnlen function is only defined in POSIX.1-2008.
It is missing on Solaris 10 or Mac OS X 10.6 for example.
> provide a workaround for missing strnlen #25

- docs/zziplib.html
- zzip/zip.c
__zzip_parse_root_directory: Check if rootsize is non-0 and rootseek lies within the archive. Fixes CVE-2018-7726 and issue/41
> __zzip_parse_root_directory: Check if rootsize is non-0 and rootseek

- zzip/__string.h
If `strn_dup` is not available on the compiling system, a custom version is compiled into `zziplib`. This version uses `malloc`, but there is no include of `stdlib.h` since e78b8d3077ce16e5433020f6098b5120c27ae3e9 moved the include into the `ifdef` of `strnlen`.
This enables compiling under MinGW for instance.
> Fix _zzip_strndup if strndup is not available

- zzip/zip.c
When __zzip_parse_root_directory() does not assign hdr0 to *hdr_return because p_reclen is NULL, hdr0 must be free'd locally.
> One more free() to avoid memory leak.

- bins/unzzip.c
- bins/unzzipcat-big.c
- bins/unzzipcat-mem.c
- bins/unzzipcat-mix.c
- bins/unzzipcat-zip.c
- test/zziptests.py
Moved common code from unzzipcat-*.c to unzzip.c within "bins":
* exitcode()
* remove_dotdotslash()
* makedirs()
* create_fopen()
> Bins code cleanup

- bins/unzip-mem.c
- test/zziptests.py
When verbously listing a ZIP file with directories, a "Floating point exception" occurs because the uncompressed size "usize" is 0. The fix is to print 0% when usize is 0.
Reproducer:
mkdir d; for i in $(seq 1 10); do echo This is line $i; done > d/file.txt
zip -9r ZIPfile.zip d
unzip-mem -v ZIPfile.zip
Floating point exception
> Prevent division by zero

- test/CMakeLists.txt
Some fixes to CMake that I found while experimenting with Travis CI. My systems have zziplib installed, but Travis doesn't, which is how I found the include errors. I'll propose a Travis CI setup as soon as this PR is merged.
More details in the commit messages.
> CMake fixes

- test/zziptests.py
The test suite currently has some platform-specific quirks, most importantly it expects on glibc-style error messages. This PR fixes all platform-specific quirks that I've experienced on my system so that the test suite now passes.
> Improve cross-platform compatibility of test suite

- docs/make-doc.py
- docs/zzipdoc/commentmarkup.py
- docs/zzipdoc/docbookdocument.py
- docs/zzipdoc/functionlisthtmlpage.py
- docs/zzipdoc/htm2dbk.py
- docs/zzipdoc/htmldocument.py
- docs/zzipdoc/textfile.py
Python3 removed support for the except Exception, e syntax this is
supported since Python 2.6
> docs: convert exception statements to Python 3 compatible

- zzip/__string.h
- zzip/format.h
- zzip/fseeko.c
- zzip/info.c
- zzip/memdisk.c
It really is mostly uninteresting fixes, most of them caused by CMake including "-Wsign-compare". I guess it's good to have them anyway to enable for clean builds with "-Werror". More info is in the commit messages, just in case the fix is debatable.
> Fixes to various compiler warnings

- zzip/fseeko.c
In case of error, the buffer may be freed twice: First time by the line 420, second time in the error2 label.
> fseeko.c: fix possible double free of buffer

- docs/zzipdoc/docbookdocument.py
Commit 5b660a3 (Merge pull request #72 from jelly/python3, 2019-08-04)
introduced a conversion to use new-style Python exceptions.
The conversion introduced a new print statements, though, breaking
compatibility with Python 3 again.
Convert the statement to use the print function, instead.
> zzipdoc: convert use of print statement

- zzip/memdisk.c
- zzip/zip.c
There's various warnings in the generated documentation either due to
missing links or to mistaken use of simple comments `/* */` instead of
docstyle comments `/** */`. Fix some of these by converting to docstyle
comments or fixing the referenced function names.
> docs: fix various warnings

- SDL/CMakeLists.txt
Just like described in commit 892dea3b82208654cc9f57ffc4ef555d0d934cf5, the `CMAKE_INSTALL_INCLUDEDIR` variable can be absolute path so simply appending it to `\${prefix}` might not work.
> build: Produce more correct pc file with zzipsdldir

- zzip/CMakeLists.txt
We've noticed that on macOS the library symlinks were not creating. Turns out, the condition
https://github.com/gdraheim/zziplib/blob/c3de4fe291ab6756593a0ef6bad007ddd3953e00/zzip/CMakeLists.txt#L302
was silently failing for us. This happens because the names of the libraries are generated differently for apple, we get `libzzip-0.13.0.71.dylib` when the code in zziplib expects `libzzip-0.dylib.13.0.71`.
https://gitlab.kitware.com/cmake/cmake/-/blob/742ff97f809410055b22405a6b5728e72c458683/Source/cmGeneratorTarget.cxx#L5890-5903
Also a related thread:
https://cmake.org/pipermail/cmake/2013-February/053605.html
cc @jtojnar
> zzip/CMakeLists.txt: fix for macOS

- test/zziptests.py
It fixes https://github.com/gdraheim/zziplib/issues/120 by adding `123` exit code which is macOS's way to return `-8`.
It also fixed minor differences in output.
> Fixed tests on macOS

- test/zziptests.py
MacPorts ships different version of `unzip` and `zip`. This small pull request adjusts tests to supporting them.
Closes https://github.com/gdraheim/zziplib/issues/123
> support of MacPort's zip and unzip

- zzip/CMakeLists.txt
zzip/CMakeList.txt uses custom build targets to create symlinks from (normaly versioned) build results to unversioned file names. These targets are executed unconditionally, every time a build is started, regardless of the existence of the target.
Debug builds generate unversioned libraries. The build targets therefore overwrite existing files with recursive links.
Create custom targets depending on the target file plus custom build commands containing the symlink creation, thereby ensuring that symlinks are only created if the link target is missing.
> ZZIP_LIBLATEST: create symlinks only if target is missing

- zzip/CMakeLists.txt
`gcc-4.2` does not accept `-Warray-bounds` flag, and the build fails. Once the flag is excluded, `libzzip` builds fine.
PR adds a relevant condition to CMakeLists.
> libzzip: do not use -Warray-bounds with gcc-4.2

- zzip/CMakeLists.txt
- zzipwrap/CMakeLists.txt
Export cmake targets so the users can easily use zziplib in cmake.
Fixes #134.
> [cmake] Export targets

- SDL/SDL_rwops_zzip.c
- zzip/mmapped.c
Clang16 and GCC 14 will make incompatible-function-pointer-types and incompatible-pointer-types and error by default. 
This patch sets the functions return and parameter types to the correct expected types and casts to the expected pointer.
See also: https://wiki.gentoo.org/wiki/Modern_C_porting
Bug: https://bugs.gentoo.org/919066
> fix incompatible pointers

- zzip/fseeko.h
Line 24 in `zzip/fseeko.h` opens the `extern "C"` bracket. This bracket needs to be closed at the end of the file.
> zzip/fseeko.h: Fix closing extern C bracket

- zzip/zip.c
already closed by `zzip_dir_fdopen_ext_io` in case of error.
> Fix invalid file descriptor close

- zzip/CMakeLists.txt
- zzipwrap/CMakeLists.txt
Enable `ZZIP_LIBLATEST` only in Release mode to avoid the following build failure raised since commit 0e8d35f92efb680c81f6ec1fca9f11d173dce389 and c835ad662a91b3df041a2144e11f932cfa4f98b4 because `RELEASE_POSTFIX` will be empty if `CMAKE_BUILD_TYPE` is set to `Debug` resulting in the symlinks overriding the libraries:
```
make[3]: stat: zzip/libzzipfseeko.a: Too many levels of symbolic links
make[3]: *** No rule to make target 'zzip/libzzipfseeko.a', needed by 'bins/unzzip-big'.  Stop.
```
Fixes:
- http://autobuild.buildroot.org/results/9cd4147486f32d642513ba14efca3a02d5745ab9
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> CMakeLists.txt: enable ZZIP_LIBLATEST only in Release mode

- zzip/__string.h
This is a tiny patch to avoid compiler warning.
Best regards,
> zzip/__string.h: cast to avoid compiler warning

- zzip/CMakeLists.txt
`include/zzip` contains a header named `stdint.h`. This headers hides the compiler's `stdint.h` when a consumer links to the exported target, resulting in errors such as (cf. x64-linux in https://dev.azure.com/vcpkg/public/_build/results?buildId=78568):
~~~
error: '::int8_t' has not been declared
~~~
and (cf. x64-windows in https://dev.azure.com/vcpkg/public/_build/results?buildId=78568)
~~~
...\cstdint(31): error C2039: 'int_least8_t': is not a member of '`global namespace''
...\cstdint(31): error C2873: 'int_least8_t': symbol cannot be used in a using-d
~~~
According to the test file, the canonical pattern is `#include <zzip/zzip.h>`.
> Fix exported interface include dir

- zzip/CMakeLists.txt
Installed cmake module describes library so it should be installed in `${CMAKE_INSTALL_LIBDIR}/cmake/zziplib`.
> install cmake module in proper path

- zzip/zip.c
Fix the #164 where extra_ptr could be alocated without enough bytes to check the magic value.
Indeed, ZZIP_EXTRA_ZIP64_CHECK, or later in the code, will call ZZIP_GETEXTRA() where it get 2 first bytes to check the magic number. 
However, there is not any verification about the size allocated for `extras_ptr`, where by the value of `u_extras`, `extras_ptr` could be allocated of 1 byte (what happened with the provided POC in the bug description). We should be sure that `u_extra` allocates the `extras_ptr` with more that 2 bytes, or better, at least same value of the size of the `zzip_extra_zip64` struct.
> parse_root_dir: Verify size of extra obtained

- zzip/zip.c
* When ZZIP_DISK64_TRAILER defined we must check if the tail obtained have the size of the zzip_disk_trailer struct. end - tail should be at least >= of the size but not size - 2.
* Fix #165
> fetch_disk_trailer: Don't truncate the size verif

- zzipwrap/CMakeLists.txt
- zzipwrap/Makefile.am
- zzipwrap/Makefile.in
From a previous commit 4b2b33f379e508a41a9e43009db921866955a02f, zzip's .pc files has been moved from $libdir/pkgconfig to $datadir/pkgconfig.
Should we do the same for zzipwrap ?
> move zzipwrap's .pc from $libdir to $datadir

- SDL/CMakeLists.txt
In `SDL/CMakeLists.txt`, `sdl2` was detected but `sdl` was written in output .pc file. It should be `sdl2` instead.
> Requires sdl2 rather than sdl for pkgconfig file
